version: '3'

services:
  bind:
    image: ubuntu/bind9
    restart: unless-stopped
    volumes:
      - ./named.conf:/etc/bind/named.conf:rw
      - ./bind.d:/etc/bind/named.conf.d:rw
      - ./cache:/var/cache/bind:rw
      - ./zones:/var/lib/bind:rw
    ports:
      - '53:53/udp'
    networks:
      dns:
        ipv4_address: 172.25.0.2

networks:
  dns:
    ipam:
      config:
        - subnet: 172.25.0.2/29
